name: Update Data from API

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily, adjust as needed
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Update Data from API
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # Replace with your API endpoint
          API_ENDPOINT="https://example.com/api/data"
      
          # Fetch data from the API and echo the status code
          STATUS_CODE=$(curl -s -w "%{http_code}" -o data.json $API_ENDPOINT)
          echo "HTTP Status Code: $STATUS_CODE"
      
          # Check if the request was successful (status code 200)
          if [ "$STATUS_CODE" -eq 200 ]; then
            # Configure Git
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
      
            # Commit and push the changes
            git add data.json
            git commit -m "Update data from API"
            git push
          else
            echo "API request failed with status code $STATUS_CODE"
          fi


      - name: Complete
        run: echo "Data update completed"
